services:
  db:
    image: postgres:16
    container_name: arrangement-db
    environment:
      POSTGRES_DB: arrangement
      POSTGRES_USER: arrangement_user
      POSTGRES_PASSWORD: arrangement_pass
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: