spring.application.name=arrangement-app
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/arrangement
spring.datasource.username=arrangement_user
spring.datasource.password=arrangement_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true